### PR TITLE
Fixed run time problem in hadron elastic process

### PR DESCRIPTION
**Pull request by civanch**
Two fixes are added, which are available in Geant4 master:
1) fixed run time computations for hadron elastic process
2) fixed warning on "unused variable" in G4CoupledTransportation

Both are useful for CMSSW.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_13_0_GEANT4_X

**Comment by civanch** [comment]
@smuzaffar , is it possible to test these fixes before the pre-release is out?

**Comment by smuzaffar** [comment]
Only testing we can do is to build/run G4  IB, once PR tests are done then we can merge and build an IB for you to do the testing

**Comment by smuzaffar** [comment]
please test for CMSSW_13_0_GEANT4_X

**Comment by civanch** [comment]
@smuzaffar , yes, it is clear. Unfortunately, I was too fast - one file should be redone and recommitted, because inside Geant4 branch there was also development, not only bug fix. I will try make it and update the PR.

**Comment by smuzaffar** [comment]
> @smuzaffar , yes, it is clear. Unfortunately, I was too fast - one file should be redone and recommitted, because inside Geant4 branch there was also development, not only bug fix. I will try make it and update the PR.

ok, feel free to start the tests (using `please test for CMSSW_13_0_GEANT4_X` comment ) once you are done with your changes

**Comment by civanch** [comment]
please test for CMSSW_13_0_GEANT4_X

**Comment by smuzaffar** [comment]
@civanch , which PR tests are running, you can use /cvmfs/cms-ci.cern.ch/week0/cms-externals/geant4/68/30029/CMSSW_13_0_GEANT4_X_2023-01-15-2300 area to run local tests e.g. you can run the following to set the env
```
cd /cvmfs/cms-ci.cern.ch/week0/cms-externals/geant4/68/30029/CMSSW_13_0_GEANT4_X_2023-01-15-2300
cmsenv
cd /tmp
# run tests
```

**Comment by smuzaffar** [comment]
@civanch , build and relvals look good, if this is OK then I would like to merge it and build an IB based on it now

**Comment by civanch** [comment]
@smuzaffar , would be great

**Comment by smuzaffar** [comment]
@civanch , GEANT4, G4VECGEOM and LTOG$VECGEOM IBs are now available with this change. Please run your tests as we might have to build 13.0.0.pre3 today.

**Comment by civanch** [comment]
@smuzaffar , I have run simple tests for 13_0_0_G4VECGEOM_X_2023_01-17-23 - results as expected. 13_0_0_LTOG4VECGEOM_X_2023-01-17-2300 give similar results but much less CPU advantage than expected 3.5%. Of course, my tests are not ideal and I saw similar effects for other SIM improvements - performance of SIM does not want to be improved.

**Pull request merged**
