### PR TITLE
Fixed Physics List destruction

### PR DESCRIPTION
**Pull request by civanch**
Address  cms-sw issue #34271

### CODE REVIEW

**Comment by civanch** [comment]
This PR needs extra commit - not yet ready for test.

**Comment by civanch** [comment]
please test

**Comment by smuzaffar** [comment]
@civanch , by default bot will test it against normal 12.0.X IBs. Shouldn;t we test it against the special G4 Ibs?

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_G4VECGEOM_X

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_GEANT4_X

**Comment by civanch** [comment]
@smuzaffar , thanks! By the way, all 3 tests should pass (my expectation).

**Comment by civanch** [comment]
@smuzaffar , I do not thing problem of the test connected with this PR, likely it is due to inconsistency of IB and this new branch.

**Comment by smuzaffar** [comment]
@civanch , yes we are changing a lot python packages this was due to missing llvm python2. This has been fixed now but there is no geant4 IB yet based on the latest externals. Let me build a geant4 IB so that we can test this PR

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_GEANT4_X

**Comment by civanch** [comment]
@smuzaffar , there is no regression in several WFs. It seems not to be connected with this PR.

**Comment by civanch** [comment]
@smuzaffar , can test be restarted ?

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , I suspect that failed tests are not related to this PR.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@civanch , there are too many comparison failures. Do you understand those? were these expacted with this change?

**Comment by civanch** [comment]
@smuzaffar , this fix is only in the class destructor, so cannot affect run time. I suspect that problem is in what compared to what. This patch should be put on top of 10.7.2, if it is compared with the master, then we compare 10.7.1 and 10.7.2.

**Comment by smuzaffar** [comment]
yes we are currently comparing 10.7.1 with 10.7.2+patch. So how do you suggest we proceed? We get this in GEANT4 IB and then build geant4 release to validate 10.7.2?

**Comment by civanch** [comment]
@smuzaffar , yes, I think this PR can be merged to this 10.7.2 branch and it would be good to have a new IB 12_0_0_pre4_G410.7.2_VecGeom

**Pull request merged**
