### PR TITLE
CMS private patch modification to reduce hadronic response.

### PR DESCRIPTION
**Pull request by civanch**
This is prepared for DEVEL branch only.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , @degano , @iahmad-khan , would it be possible to start testing of this PR (my request has no value).

**Comment by ghost** [comment]
@civanch we do not have any automatic testing for external packages. We will now test it from your own branch.

**Comment by iahmad-khan** [comment]
@civanch while testing it. 

https://github.com/cms-sw/cmsdist/pull/2323

it results in error:

```
CMake Error at cmake/Modules/Geant4MacroLibraryTargets.cmake:109
(add_library):
   Cannot find source file:

/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/BUILD/slc6_amd64_gcc530/external/geant4/10.02.p01-cms/geant4.10.02.p01/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsFTFP_BERT_ATL.cc

   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
   .hxx .in .txx
```

I think there is some file missing from the commit.

**Comment by civanch** [comment]
@iahmad-khan , yes, you are right, forgotten class is added.

**Comment by ghost** [comment]
@iahmad-khan you forgot to start the tests after your commit :)

**Pull request merged**
